const actionTypes = {
    AUTH: "AUTH",
    LOGOUT: "LOGOUT",
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    CREATE: "CREATE",
    DELETE: "DELETE",
    UPDATE: "UPDATE",
    CREATEORDER: "CREATEORDER",
    SET_ORDERS: "SET_ORDERS",
    SELECTED_ORDER: "SELECTED_ORDER",
    REMOVE_SELECTED_ORDER: "REMOVE_SELECTED_ORDER",
    DELETEORDER: "DELETEORDER"
}

export default actionTypes